language: python

cache: pip

python:
- '3.5'
- '3.6'
- '3.7'

install:
- pip install .
- pip install -r requirements-dev.txt

script:
- nosetests

jobs:
  include:
  - stage: PyPI release
    python: '3.7'
    script: skip
    deploy:
      provider: pypi
      user: Pr0Ger
      password:
        secure: BH1dlIcbjoIF3AJrJwPW/UXfs+8eWfNUzkVBID+5csOvEd8/YEPmyxbabUSEVGhc5irMsPEGZVZIdYShQep6Hi/01kXgvrZDBEqHnRMJ79FMv7xiKyt98KMVutmVDnzd+PgAcGBomLYb0BlQEtkD1DlwtoxqOh+7Rz7+yqsRy05PbqECgvF1FalFh4lzNHFUoa1smdHwA6olav4dWHdjCnE4GEXAfQUBBvDSpQm+Hj4OUpB5MetYiKHoBVGUibwq2QZ51V1AtSFs/53FcvCmOzxVTBgXgJd0r+B3z2Au/S8x/ERvSOpXKDK0FBr3JalpjhDxIfetMnULc1fjwaTdJ99auMoPn15MnCzQ4WPMHL0DLrVLPzkr0hMe2ENp8B4ULHmhzJdppqh7S3ptBpkH2zGQWS5NIleJhvOeL2+jrI9stTnaadEQqKqUMdGLxqPgQGrggJxEPWQ22DpSYIHmczxWsRqv7gKm/cOq3w5lzbvqZ+8OWxpORv310k4BRxws+jec8YzSBLo5VN4CldMIIck3TKYwjiPbZQMz2qfuSok1tH8VyJRKqM51lfF/5U7qA7pnz9aVufvrA6u61wn+9MKhtr5kzmHnZEQOYvKSVNQqr9xBhBHianT/wRTh1LrilXnzX9CWKlRcGTXGxrxpc+g2LejxRvxPG7hXOyt0vbM=
      distributions: sdist bdist_wheel
      on:
        tags: true

notifications:
  email: false
  slack:
    secure: hqbqt/zePs9ognCQT/IlLmRBpTxudSBR88GK/Qu0GOJZhuBsFvUbHaDKkTsIPYoLsZPKYss0tpKsRQJG0GlO8da7d/raR4gSNI5y0ypso5ttN+OgLf4pa1bUwz0Q39aDFcuSG9aZEU134hk19KYFxz3h+gLI5C51mnnm2qOK1goq+ZNTtIz42y7kxRnF4opExLS9+ZTUxV2eA5lEvgoju6PVXfu1CkzPZKZt3XXnl3G2LGo4pitemiOIBSiVHLuakLmZ5z7IyVTbsB2Sh+2HoTdvGpdxNJcy0wDbvnZ0ZE3otrCkggaTQJ8uMEygsx8JafmDCC3sAosCqftj+SG9bG9LSmypizmipNEClSq5iKEtniGhoR1Imzbk7b5yth6q3TETY/fYFt9hATDBbn+IS0ZD0kJaVfN5Tgi6fiFtKbHPl9XxdLDffPDv5/AvSlY0CaDpTeN8j3YkMHSyuSN+u+qyai5KTWi4b2WZDY5MklTO6/3Kems/rYatCYjthzW94Di2rNDxnESeUmWy94npRxYg+HBVlVO5kG/ujHwwT5jU6icOcIJrtQAnJfTApyrEvqYtHUw0WATq/aTSYDEwQvJtV9xPX1R3XuDSZ+MBXobo+nplStkMdo0FmHcYrwi0oAohnmMu0jFMuByoY8crawrKB3EC/0/BHJvRs6QTWSE=
